name: Bug Report
description: Report a problem with ioctx-py
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more information you provide, the better we can help you.

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: A clear and concise description of the bug
      placeholder: When I do X with ioctx, I see Y but expected Z
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior (include code example if possible)
      placeholder: |
        ```python
        from ioctx import FakeIO, HttpResponse

        # Your code that demonstrates the issue
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include any error messages/tracebacks)
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: Which Python version(s) have you observed this behavior with?
      multiple: true
      options:
        - 3.9
        - 3.10
        - 3.11
        - 3.12
    validations:
      required: true

  - type: input
    id: ioctx-version
    attributes:
      label: ioctx-py Version
      description: Which version of ioctx-py are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Additional information about your environment
      placeholder: Operating system, other relevant packages, etc.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Before Submitting
      description: Please confirm you've completed these steps
      options:
        - label: I've searched for similar issues in the repository
          required: true
        - label: I've updated to the latest version of ioctx-py to verify the issue persists
          required: true
