name: Feature Request
description: Suggest a new feature or enhancement for ioctx-py
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for ioctx-py! Please fill out this form as completely as possible.

  - type: textarea
    id: problem
    attributes:
      label: Related Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when [...] when using ioctx-py
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see [...] functionality that would help with [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        I've tried working around this by [...]
        or
        Another approach could be [...]
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If you can, provide an example of how this feature would be used
      placeholder: |
        ```python
        # With this new feature, I could do:
        from ioctx import NewFeature

        # Example code demonstrating the feature
        ```
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: This would help in scenarios like [...] or be useful when [...]
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Before Submitting
      options:
        - label: I've searched for similar feature requests in the repository
          required: true
        - label: I've checked the documentation to make sure this feature doesn't already exist
          required: true
        - label: I'm willing to help implement this feature if needed
          required: false
